### ISSUE TITLE
[BUG] Data Reload - works only one time

### ISSUE THREAD

**Issue by konne** [q-masters/vsqlik#485]
Reload of a main.qvs works perfect after open the first time.
If the reload is done, the reload button don't work anymore.
I had to close the main.qvs, reopen and than it is working only onetime again.

**Comment by r-hannuschka** [comment]
Seems to be only be a problem if we lost the focus on the text editor, that means if i go down to the output and click into this one i cant start reload data again until i clicked into the script section.

Scenario 1: open main.qvs -> click into output and then directly start reload data not working (the open document is now the output)
Scenario 2: If i open a second file for example a var.yaml so 2 tabs exists on top, i can switch back to main.qvs and reload data is running
Scenario 3: Start reload, open new file (anything else) switch back it reload data is running.

I will listen to the event onDidChangeActiveTexteditor -> so i know when we have switched to anywhere if this is the output i know it is the last open document, maybe this will work. But this does not explains since only close was working for you :/.

**Comment by r-hannuschka** [comment]
@konne i added the fix if we lost the scope on the main document data reload was not working anymore, to keep things simple we can grab all visible text documents on the window (which is the one tab) and try to find the main.qvs file, if one exists triggering reload-data should now work.

can you test this again please ?

**Comment by r-hannuschka** [comment]
as discussed,

- [ ] check active texteditor contains the main.qvs file start directly
- [ ] check all visible text editors for the main.qvs file
- [ ] if multiple text editors exists with the main.qvs file (split screen for example) show information message
