### ISSUE TITLE
Show diff if server version of script is different to unsaved version of script in VSQlik.

### ISSUE THREAD

**Issue by davidwales** [q-masters/vsqlik#543]
**Is your feature request related to a problem? Please describe.**
If you make changes to a script in VSQlik, then make changes in the Qlik Sense load script editor, then come back to VSQlik, it will automatically discard your local changes in favour of what's on the server.

**Describe the solution you'd like**
It would be good if a diff could be shown in this case, allowing you to choose which conflicting changes to keep, and which to reject.

**Describe alternatives you've considered**
In theory, you would only ever edit in VSQlik, and never make changes in the Qlik Sense script editor. However, sometimes you forget!

**Comment by r-hannuschka** [comment]
@davidwales i will start this one as soon as possible, it is currently a very good and valid use case. We allways assume only one edit the app, but i can also think about 2 will edit the application or you are at a presentation and find a small bug or changes so in this case you maybe edit the app (sheets, variable) directly in qlik sense and not open your editor, connect, find the file edit save and reload the data.

So i will implement this not only for an app, also variables, sheets, dimension and so one should take care about that.

**Comment by r-hannuschka** [comment]
@davidwales since i'm nearly done with that i think i faced that issue in order this workflow:

1. Open Script
2. Edit script in vscode and save
3. i toggle to server (new window) and open that script see my changes from vscode and edit here
4. now i come back to vscode (it becomes focus) in this case it read the data again from the server

So fine it was allready up to date okay cool.

Bad things happens here i open both vscode and the browser at the same time and then start to edit in vscode and after that i edit some things in the browser. The same behavior as above with the difference the browser do not notificate me someone has changed something, simply write now my local changes gets lost in vscode since the server wins that fight. Could also happens if any other person starts edit the script.

Solution currently:

If you open the script in vscode it becomes "locked" (cached as local version) and starts to listen on app.changed event. Now if someone edit that script (browser / vscode on same/other computer) and save it, we get notified about that the script is different now and a diff shows up. And it stays locked until you close the file.

So now for example you can do peer programming on same script with multiple friends, should be working even if vscode lost the focus (some other important app will openend) and switch back to vscode.

One thing: 

If you close the Script (saved) the next one who save win's and override the script on the server and your changes are lost if your reopen the script.

To avoid that we need something like a local change history but this becomes an other story.

Would this solve your issue on this ?

Best regards,
Ralf

**Comment by davidwales** [comment]
@r-hannuschka Are you describing the following situation?

1. Script is open in *both* Qlik Sense **AND** VS Code
2. You save and close the script in VS Code
3. The script in Qlik Sense hasn't seen your changes, because it was already open, and you haven't reloaded the page.
4. You make a different change in the script in Qlik Sense and it autosaves.
5. This overwrites your VS Code changes, because Qlik Sense didn't think to check if there were changes, and assumes that it's the only tool used to edit Qlik scripts.

**Comment by konne** [comment]
@davidwales 

>Is there a way to tell Qlik Sense to refresh the load script?

not really, just try it with two browsers and qlik itself. Even if you make a reload in one app it doesn't fetch the script in the second app.

>Down the track, it would be good ... local GIT ...

Yes, this is also on the roadmap. I have it on my wishlist for Xmas, but be honest the chance is maximum 50%.

**Comment by konne** [comment]
@r-hannuschka 
what we do is to save a copy of our last vscode saved script in an extra app property and if you reopen the app again it warns you that changes are done outside of vsqlik and ask you what to do.

**Comment by r-hannuschka** [comment]
Adding the custom properties was not working for, and if i'm right this is not possible for qlik sense server.

@see https://help.qlik.com/en-US/sense-developer/2.2/Subsystems/EngineAPI/Content/Structs/NxAppProperties.htm
